### ISSUE TITLE
Transition period to disable BIPs?

### ISSUE THREAD

**Issue by hakunin** [BitcoinHardfork/bitcoin#8]
Hi,
regarding the recent events on testnet, is there a plan to temporarily disable BIPs in case an attacker points mining power into the network in an effort to cause havoc?

Is this scenario being analysed / What needs to be addressed?

**Comment by luke-jr** [comment]
I'm not sure what you're talking about. Bitcoin Improvement Proposals is merely a standardised way of documenting cross-implementation improvements to Bitcoin. It's not software... there's nothing to disable.

**Comment by hakunin** [comment]
Here is the testnet issue https://github.com/btc1/bitcoin/issues/65 I don't know much of the details, but from what I've gathered someone with mining power came to testnet and caused problems since he had so much mining power he accidentally activated one of the BIPs.

So I was wondering if there is anything apart of changing PoW that needs to be though about in case someone with bad intentions pointed a lot of mining power into the fork.

**Comment by luke-jr** [comment]
That was just due to incompetence (we even warned them about it, and suggested a better solution...).

The closest thing that would affect us would be if we ended up changing the PoW algorithm and didn't have any mining software that could actually mine it. But BFGMiner is modularised so it's easy to add algorithms - mostly copy/paste from the hardfork code, really.
